### ISSUE TITLE
Animation blocking

### ISSUE THREAD

**Issue by Elipasousa** [HIkaruSato/PPEffectButton#1]
Hey, I automatically migrated your code to swift 3.0 ([here](https://github.com/Elipasousa/PPParticleButton)) so I could use it in my project. I added the SpriteKit Particle file, changed my button's class and when I tap the button the particles do appear. But after just a second they freeze and stay frozen until disappearing. When I tried to run your example (after the swift 3.0 migration), the same happens. Are you aware of this problem?

**Comment by HikaruSato** [comment]
Sorry to be late. I did not recognize it. I will investigate.

**Comment by HikaruSato** [comment]
Thank you for raising this issue.

**Comment by HikaruSato** [comment]
Fixed this issue.
